import type {Metadata}
from 'next'
import {Inter} from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata : Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({children} : {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className='min-h-screen w-full bg-white'>
                    <nav className="fixed top-0 w-full bg-transparent z-50 p-4">
                        <div className="flex justify-center p-4">
                            <a href="#" className="hover:text-gray-800 mx-4">Home</a>
                            <a href="#" className="hover:text-gray-800 mx-4">Our Story</a>
                            <a href="#" className="hover:text-gray-800 mx-4">Wedding Details</a>
                            <a href="#" className="hover:text-gray-800 mx-4">RSVP</a>
                        </div>
                    </nav>
                    {children}
                </main>
            </body>
        </html>
    )
}
