import type {Metadata}
from 'next'
import {Calligraffitti, Inter} from 'next/font/google'
import './globals.css'
import Link from 'next/link';

const inter = Inter({weight: '400', preload: false});

export const metadata : Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({children} : {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main style={{minHeight: '100vh', width: '100%', background: "#eee"}}>
                    <nav className="fixed top-0 w-full bg-transparent z-50 p-4">
                        <div className="flex justify-center p-4">
                            <Link href="/" className="hover:text-gray-800 mx-4">Home</Link>
                            <Link href="/ourstory" className="hover:text-gray-800 mx-4">Our Story</Link>
                            <Link href="/wedding" className="hover:text-gray-800 mx-4">Wedding Details</Link>
                            <Link href="/photos" className="hover:text-gray-800 mx-4">Photos</Link>
                        </div>
                    </nav>
                    {children}
                </main>
            </body>
        </html>
    )
}
